export const JokeData = [
    {
      category: "Python Jokes",
      jokes: [
        "Why do Python programmers prefer snake_case? It’s constricting!",
        "What’s Python’s favorite dance? The code shuffle.",
        "Why do Python developers love functions? Because they always return something.",
        "Python programmers rarely use multi-threading. They don’t want to deal with the GIL-t.",
        "What’s a Python’s favorite snack? A byte.",
        "Why did the Python throw a fit? It had too many IndentErrors.",
        "Python walks into a bar and orders a drink. The bartender says, 'No semicolons here!'",
        "Why was the Python programmer so calm? He knew he could handle exceptions.",
        "Python devs always win arguments; they know how to assert themselves.",
        "Why don’t Python programmers like classes? They prefer everything to be dynamic.",
        "Python developers are like snakes—they shed unnecessary lines of code.",
        "What’s a Python’s favorite movie? The Matrix.",
      ],
    },
    {
      category: "JavaScript Jokes",
      jokes: [
        "Why was JavaScript single? It didn’t know how to handle promises.",
        "JavaScript: The language where everything is true, except `false` and `null`.",
        "Why do JavaScript developers hate dates? Because they’re always buggy.",
        "JavaScript is like a relationship: It’s messy but works.",
        "What did the JavaScript array say to the string? 'Join me.'",
        "Why do JavaScript developers prefer maps over objects? They have a better sense of direction.",
        "JavaScript walks into a bar. All the drinks are `undefined`.",
        "Why didn’t the JavaScript function get any love? Because it didn’t have any arguments.",
        "How does JavaScript calm down? It uses `this`.",
        "Why do JavaScript programmers avoid static parties? Because they prefer dynamic vibes.",
        "JavaScript devs always keep an eye on their scope.",
        "What’s JavaScript’s favorite type of food? Callbacks.",
      ],
    },
    {
      category: "Bug Jokes",
      jokes: [
        "Why did the bug go to therapy? It had too many unresolved issues.",
        "Debugging: Being the detective in a crime movie where you are also the murderer.",
        "What’s a bug’s favorite vacation spot? A sandbox.",
        "Why are bugs so loyal? They stick around forever.",
        "How do bugs start their day? With a cup of Java.",
        "What do you call a bug with no friends? Deprecated.",
        "Why was the bug so popular? It knew how to crash a party.",
        "Bugs don’t argue; they assert themselves.",
        "Why do programmers love bugs? They keep their jobs secure.",
        "Bugs are like bad roommates: They show up uninvited and never leave.",
        "What do bugs do at a party? Cause a stack overflow.",
        "What’s a bug’s favorite instrument? The debugger.",
      ],
    },
    {
      category: "AI and Machine Learning Jokes",
      jokes: [
        "Why did the AI get fired? It couldn’t think outside the bot.",
        "Machine Learning algorithms can predict everything, except their own bugs.",
        "AI’s favorite movie? Artificial Intelligence: The Terminator.",
        "Why did the AI start meditating? To reduce overfitting.",
        "AI walks into a bar. Bartender: 'I’m sorry, I can’t serve you.' AI: 'Why not?' Bartender: 'You lack class.'",
        "What do you call a lazy machine learning model? Overfit and underperforming.",
        "Why was the neural network so happy? It finally found its weights.",
        "AI is great at chess but terrible at checkmates—it always gets stuck in loops.",
        "How does AI stay humble? It has regularization.",
        "Why do ML engineers never trust AI? Too many false positives.",
        "AI loves data; it’s a true romantic at heart.",
        "What do AI and pirates have in common? Deep learning.",
      ],
    },
    {
      category: "Database Jokes",
      jokes: [
        "Why did the database administrator break up with their partner? They couldn’t handle the relationships.",
        "SQL walked into a bar and saw two tables. It said, 'Mind if I join you?'",
        "Why do databases never get lost? They always have indexes.",
        "What’s a database’s favorite snack? Chips and joins.",
        "Why don’t databases like mountains? Too many peaks and locks.",
        "How do you ask out a database? 'SELECT * FROM crushes WHERE cute = true;'",
        "Why do databases love books? They have chapters (schemas).",
        "How do databases stay in shape? They normalize.",
        "What do you call a database with no rows? Empty and lonely.",
        "Why do databases love singing? Because they have keys.",
        "What’s a database’s favorite song? 'Join Me!'",
        "Why was the database always stressed? Too many constraints.",
      ],
    },
    {
      category: "Networking Jokes",
      jokes: [
        "Why don’t networks trust each other? Too many bad connections.",
        "What’s a network’s favorite pick-up line? 'Are you a packet? Because I’d route you anywhere.'",
        "Why did the router break up with the switch? It felt disconnected.",
        "Why are networks always calm? They know how to handle traffic.",
        "What’s a network engineer’s favorite drink? IP-Tea.",
        "Why did the packet cry? It got dropped.",
        "What do networks say during an argument? 'Ping me if you need me.'",
        "Why did the IP address need therapy? Too much subnetting.",
        "What do you call a happy network? Well-connected.",
        "What’s a network’s favorite sport? Ping pong.",
        "Why did the firewall go to the party? To block all the bad vibes.",
        "How do networks flirt? They send pings.",
      ],
    },
  {
      category: "Linux Jokes",
      jokes: [
        "Why did the Linux admin break up with their girlfriend? She had too many dependencies.",
        "Why do Linux users love coffee? It keeps their processes awake.",
        "What’s a Linux user’s favorite band? The Kill -9s.",
        "How does a Linux user propose? 'sudo marry me.'",
        "Why was the Linux terminal so lonely? It always worked in isolation.",
        "Why do Linux admins never get locked out? They have root access.",
        "What’s a Linux user’s favorite drink? Open-source soda.",
        "Why do Linux commands always win arguments? They know how to pipe down.",
        "What’s a Linux user’s favorite dessert? Kernel panic pie.",
        "Why do Linux users never get viruses? They have the best shields: chmod and chown.",
        "How do Linux users stay organized? They always create a directory.",
        "What’s a Linux user’s favorite TV show? Breaking Bash.",
      ],
    },
    {
      category: "Version Control Jokes",
      jokes: [
        "Why did Git go to therapy? It had too many issues.",
        "What’s a developer’s favorite dating advice? Always commit.",
        "Why do developers love Git? It keeps their history intact.",
        "Why was the repo so happy? It had zero conflicts.",
        "Why did the branch get jealous? It thought the main branch was being merged with someone else.",
        "What’s Git’s favorite game? Push and pull.",
        "Why don’t developers trust GitHub? Too many forks.",
        "How do developers apologize? They revert their mistakes.",
        "What’s Git’s favorite type of music? Merge metal.",
        "Why do developers write bad code? So they can blame the merge conflict.",
        "Why did the Git repo have trust issues? It was always detached.",
        "What’s a Git developer’s favorite drink? Commit-Tea.",
      ],
    },
    {
      category: "General CS Jokes",
      jokes: [
        "Why was the computer cold? It left its Windows open.",
        "Why don’t computers ever get hungry? They eat bytes.",
        "Why was the computer late? It had a hard drive.",
        "What do you call a computer superhero? A Screen Saver.",
        "Why do computers hate the outdoors? Too many windows.",
        "What’s a computer’s favorite dance? The disk-o.",
        "Why don’t computers argue? They always agree to disagree.",
        "What’s a computer’s least favorite food? Spam.",
        "Why do computers never get bored? They have plenty of cache.",
        "Why was the computer stressed? It had too much on its clipboard.",
        "How do computers flirt? They send binary signals.",
        "What do you call a sad computer? A Dell in distress.",
      ],
    },
    {
      category: "C/C++ Jokes",
      jokes: [
        "Why do C programmers have such a tough time dating? They always forget to declare their love.",
        "What’s a C++ programmer’s favorite movie? The Lord of the Loops.",
        "Why do C developers hate social events? Too much dynamic linking.",
        "Why did the C++ developer quit his job? He didn’t want to deal with abstract classes anymore.",
        "What’s the scariest thing for a C programmer? Undefined behavior.",
        "Why do C++ programmers prefer elevators? Because they avoid stairs.",
        "Why don’t C++ devs play hide-and-seek? They can’t find their friends.",
        "What’s a C programmer’s favorite tool? A pointer.",
        "Why was the C developer so efficient? He reused all his variables.",
        "What do C++ devs love at breakfast? Object-oriented omelets.",
        "Why do C++ programmers hate Fridays? Too many segmentation faults.",
        "How do C programmers apologize? They nullify their errors.",
      ],
    },
    {
      category: "Java Jokes",
      jokes: [
        "Why was the Java developer always so broke? He lost his class.",
        "What’s Java’s favorite type of music? Garbage collection.",
        "Why did the Java app crash? It couldn’t find its main method.",
        "Why was the Java developer so relaxed? Because he had try-catch blocks.",
        "Why did the Java developer start gardening? He wanted to grow trees.",
        "Why don’t Java developers like to share? They’re afraid of classpath conflicts.",
        "Why did the Java program go to the therapist? It had too many inner classes.",
        "What’s Java’s favorite superhero? NullPointer Man.",
        "Why don’t Java developers like threads? They get deadlocked.",
        "How do Java developers stay in shape? They run JVM marathons.",
        "Why was the Java code so messy? It was over-abstracted.",
        "What’s a Java developer’s favorite tea? Abstract Factory Blend.",
      ],
    },
  ];
  